default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_ci if ENV["CI"]

    # Auto-increment local build number
    increment_build_number

    build_ios_app(
      scheme: "Buckit",
      export_method: "app-store",
      export_xcargs: "-allowProvisioningUpdates"
    )

    upload_to_testflight(
      skip_waiting_for_build_processing: true
    )
  end
end
